"""BIJOTEL: SpanProcessor plug-ins for OpenTelemetry GenAI."""

from bijotel.adapters import (
    AnthropicAdapter,
    OpenAIAdapter,
    Provider,
    ProviderResponse,
)
from bijotel.core.init import init, shutdown
from bijotel.decorators import trace_genai, wrap
from bijotel.layers import (
    ASTSafetyChecker,
    ASTViolation,
    Budget,
    ContainmentDecision,
    ContainmentGuard,
    DeterministicFingerprinter,
    FingerprintSpanProcessor,
    MisalignmentReport,
    ModelRegistry,
    ParetoRouter,
    Probe,
    ProbeLibrary,
    SemanticFingerprinter,
    TaskClassifier,
    ast_safety_check,
    misalignment_check,
    routing_recommendation,
    similarity_search,
)
from bijotel.policy import (
    Decision,
    PolicyDeniedError,
    PolicyEngine,
    cost_per_call_max,
    daily_token_budget,
    guard,
    model_allowlist,
    model_version_pin,
    output_length_limit,
    pii_detection,
    prompt_pattern_deny,
    rate_limit_calls_per_minute,
)
from bijotel.processors import DAGNode, MerkleDAG, export_chain, verify_export
from bijotel.regression import (
    Anomaly,
    AnomalyMethod,
    DimensionStats,
    RegressionDetector,
    compute_baseline,
)

__version__ = "0.8.0"

__all__ = [
    "ASTSafetyChecker",
    "ASTViolation",
    "Anomaly",
    "AnomalyMethod",
    "AnthropicAdapter",
    "Budget",
    "ContainmentDecision",
    "ContainmentGuard",
    "DAGNode",
    "Decision",
    "DeterministicFingerprinter",
    "DimensionStats",
    "FingerprintSpanProcessor",
    "MerkleDAG",
    "MisalignmentReport",
    "ModelRegistry",
    "OpenAIAdapter",
    "ParetoRouter",
    "PolicyDeniedError",
    "PolicyEngine",
    "Probe",
    "ProbeLibrary",
    "Provider",
    "ProviderResponse",
    "RegressionDetector",
    "SemanticFingerprinter",
    "TaskClassifier",
    "__version__",
    "ast_safety_check",
    "compute_baseline",
    "cost_per_call_max",
    "daily_token_budget",
    "export_chain",
    "guard",
    "init",
    "misalignment_check",
    "model_allowlist",
    "model_version_pin",
    "output_length_limit",
    "pii_detection",
    "prompt_pattern_deny",
    "rate_limit_calls_per_minute",
    "routing_recommendation",
    "shutdown",
    "similarity_search",
    "trace_genai",
    "verify_export",
    "wrap",
]
